### PR TITLE
[rosemacs] add xml validator for test file

### PR DESCRIPTION
**Pull request by furushchev**
- add validation logic for test tag (see http://wiki.ros.org/roslaunch/XML/test)
- enable nxml-mode for extension `*.test`

### CODE REVIEW

**Comment by gaya-** [comment]
Could you give me some more information about the ``*.test`` files? I've never seen launch files with such an extension, so I'm not sure if it's a general enough thing to be added to rosemacs.

**Comment by furushchev** [comment]
`*.test` files are the test files for `rostest`. These are almost the same format as `*.launch` files, but are usually distinguished from normal `*.launch` file by extension.
for example:
https://github.com/ros/ros_comm/blob/indigo-devel/test/test_roslaunch/test/roslaunch.test
https://github.com/ros/executive_smach/blob/indigo-devel/smach_ros/test/state_machine.test

**Comment by gaya-** [comment]
Ok, let's hope that our ROS ``*.test`` files don't conflict with any other known ``*.test`` extensions.

**Comment by gaya-** [comment]
Thanks! С наступающим.

**Comment by furushchev** [comment]
@gaya- И тебя!

**Pull request merged**
